name: Feature Request or Bug Report
description: Suggest an enhancement or report an issue that needs fixing.
title: "[TYPE]: Concise Title Describing the Issue"
labels: ["triage"] # Etiqueta base aplicada a todas las issues
assignees: []

body:
  # 1. Mandatory Description Section (Sin cambios)
  - type: markdown
    attributes:
      value: |
        ## 📝 Description (Mandatory)
        Please provide a clear and concise description of the request or the problem you are encountering.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the core problem, or what new capability should be added?
      placeholder: Describe the issue clearly...
    validations:
      required: true

  # 2. Optional Detail Section (Sin cambios)
  - type: markdown
    attributes:
      value: |
        ---
        ## 📋 Detail (Optional)
        Provide any extra context, steps to reproduce (for bugs), or detailed specifications (for features).

  - type: textarea
    id: detail
    attributes:
      label: Further Details/Steps to Reproduce (Optional)
      description: Use this space for steps to reproduce a bug, detailed specifications for a feature, or screenshots.
      placeholder: E.g., 1. Go to 'X' page. 2. Click on 'Y' button. 3. Observe Z error...
    validations:
      required: false

  # 3. Planning Status (Sin cambios)
  - type: markdown
    attributes:
      value: |
        ---
        ## 📅 Planning Status
        Is this a planned task (e.g., from a sprint backlog) or reactive work (e.g., immediate bug fix)?
  
  - type: checkboxes
    id: planning_status
    attributes:
      label: Planning Status
      options:
        - label: This is **UNPLANNED** work (e.g., an urgent fix or reactive task).
          required: false
          # IMPORTANTE: No podemos asignar etiquetas aquí porque no hay un valor único al que asociarlas
    validations:
      required: false

  # 4. Core Task Type (¡Nuevas Etiquetas Aplicadas!)
  - type: dropdown
    id: type
    attributes:
      label: Core Task Type
      description: Select the core nature of this issue (mandatory, single selection).
      options:
        - label: Feature Request
          value: feature
          # Asigna la etiqueta 'enhancement' o similar
          labels: 
            - enhancement
        - label: Bug Report
          value: bug
          # Asigna la etiqueta 'bug'
          labels: 
            - bug
        - label: Maintenance Task
          value: task
          # Asigna la etiqueta 'chore' o similar
          labels:
            - chore
    validations:
      required: true
      
  # 5. Additional Labels (¡Etiquetas Aplicadas!)
  - type: checkboxes
    id: additional_labels
    attributes:
      label: Additional Labels
      description: Select all relevant labels that describe this issue.
      options:
        - label: Tests
          labels: 
            - test
        - label: Bug Fix
          labels: 
            - bug
        - label: Collaboration Required
          labels: 
            - colaborative
        - label: CI/CD Pipeline
          labels: 
            - CI/CD
        - label: Documentation Update
          labels: 
            - documentation
        - label: Work Item: Easy
          labels: 
            - WI_Easy
        - label: Work Item: High
          labels: 
            - WI_High
        - label: Work Item: Mandatory
          labels: 
            - WI_Mandatory
        - label: Work Item: Medium
          labels: 
            - WI_Medium
    validations:
      required: false
      
  # 6. Priority (¡Etiquetas Aplicadas!)
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this issue? (mandatory priority label)
      options:
        - label: P0: Critical
          value: P0
          labels:
            - P0-Critical
        - label: P1: High
          value: P1
          labels:
            - P1-High
        - label: P2: Medium
          value: P2
          labels:
            - P2-Medium
        - label: P3: Low
          value: P3
          labels:
            - P3-Low
    validations:
      required: true
      
  # 7. Asignación de Responsables (NUEVO CAMPO)
  - type: input
    id: assignees_input
    attributes:
      label: Assignee(s)
      description: Escribe el @username de GitHub de la(s) persona(s) responsable(s) de esta Issue.
      placeholder: E.g., @usuario1 @usuario2
    validations:
      required: false

  # 8. Confirmation Checkbox List (Sin cambios)
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following.
      options:
        - label: I have searched the existing issues and this is not a duplicate.
          required: true
