name: Feature Request or Bug Report
description: Suggest an enhancement or report an issue that needs fixing.
title: "[TYPE]: Concise Title Describing the Issue"
labels: ["triage"]
assignees: []

body:
  ## 📝 1. Description (Mandatory)
  - type: markdown
    attributes:
      value: |
        Please provide a clear and concise description of the request or the problem you are encountering.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the core problem, or what new capability should be added?
      placeholder: Describe the issue clearly...
    validations:
      required: true

# 2. Optional Detail Section
  - type: markdown
    attributes:
      value: |
        ---
        ## 📋 Detail (Optional)
        Provide any extra context, steps to reproduce (for bugs), or detailed specifications (for features).

  - type: textarea
    id: detail
    attributes:
      label: Further Details/Steps to Reproduce (Optional)
      description: Use this space for steps to reproduce a bug, detailed specifications for a feature, or screenshots.
      placeholder: E.g., 1. Go to 'X' page. 2. Click on 'Y' button. 3. Observe Z error...
    validations:
      required: false

  
  ## 📅 3. Planning Status
  - type: markdown
    attributes:
      value: |
        Is this a planned task (e.g., from a sprint backlog) or reactive work (e.g., immediate bug fix)?
  
  - type: checkboxes
    id: planning_status
    attributes:
      label: Planning Status
      options:
        - label: This is **UNPLANNED** work (e.g., an urgent fix or reactive task).
          required: false
    validations:
      required: false

  ---
  ## 🏷️ 4. Core Task Type (Asigna Etiquetas)
  - type: dropdown
    id: type
    attributes:
      label: Core Task Type
      description: Select the core nature of this issue (mandatory, single selection).
      options:
        - label: Feature Request
          value: feature
          labels: 
            - enhancement
        - label: Bug Report
          value: bug
          labels: 
            - bug
        - label: Maintenance Task
          value: task
          labels:
            - chore
    validations:
      required: true
      
  # 5. Additional Labels (Asigna Etiquetas Múltiples)
  - type: checkboxes
    id: additional_labels
    attributes:
      label: Additional Labels
      description: Select all relevant labels that describe this issue.
      options:
        - label: test
          labels:
            - test
        - label: bug
          labels:
            - bug
        - label: colaborative
          labels:
            - colaborative
        - label: CI/CD
          labels:
            - CI/CD
        - label: documentation
          labels:
            - documentation
        - label: WI_Easy
          labels:
            - WI_Easy
        - label: WI_High
          labels:
            - WI_High
        - label: WI_Mandatory
          labels:
            - WI_Mandatory
        - label: WI_Medium
          labels:
            - WI_Medium
    validations:
      required: false
      
  # 6. Priority (Asigna Etiquetas de Prioridad)
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this issue? (mandatory priority label)
      options:
        - label: P0: Critical
          value: P0
          labels:
            - P0-Critical
        - label: P1: High
          value: P1
          labels:
            - P1-High
        - label: P2: Medium
          value: P2
          labels:
            - P2-Medium
        - label: P3: Low
          value: P3
          labels:
            - P3-Low
    validations:
      required: true
      
  ---
  ## 👤 7. Assignee(s) (Campo de Texto para Asignación)
  - type: input
    id: assignees_input
    attributes:
      label: Assignee(s)
      description: Escribe el @username de GitHub de la(s) persona(s) responsable(s) de esta Issue.
      placeholder: E.g., @usuario1 @usuario2
    validations:
      required: false

  # 8. Confirmation Checkbox List
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following.
      options:
        - label: I have searched the existing issues and this is not a duplicate.
          required: true
